export type TravelTheme = "family" | "honeymoon" | "luxury" | "budget" | "adventure" | "food";
export type SeoPageType = "trip-cost" | "itinerary" | "trip-plan" | "travel-guide";

export interface SeoDestination {
  slug: string;
  name: string;
  country: string;
  category: "domestic" | "international" | "region";
  overview: string;
  bestTime: string;
  visaSummary: string;
  idealDurations: number[];
  themes: TravelTheme[];
  attractions: string[];
  hotelSuggestions: string[];
  travelTips: string[];
  estimatedCostFromIndia: {
    budget: number;
    comfort: number;
    premium: number;
  };
}

export const seoThemes: TravelTheme[] = ["family", "honeymoon", "luxury", "budget", "adventure", "food"];
export const seoDurations = [3, 5, 7, 10, 14];
export const seoPageTypes: SeoPageType[] = ["trip-cost", "itinerary", "trip-plan", "travel-guide"];

export const seoDestinations: SeoDestination[] = [
  {
    slug: "goa",
    name: "Goa",
    country: "India",
    category: "domestic",
    overview: "Goa works as a short domestic escape with beaches, nightlife, cafes, heritage neighborhoods, and easy long-weekend logistics from major Indian metros.",
    bestTime: "November to February",
    visaSummary: "No visa required for domestic Indian travelers.",
    idealDurations: [3, 5, 7],
    themes: seoThemes,
    attractions: ["Baga Beach", "Fontainhas", "Dudhsagar Falls", "Chapora Fort", "Anjuna Flea Market"],
    hotelSuggestions: ["Candolim beach resorts", "Panaji heritage stays", "Anjuna boutique hotels"],
    travelTips: ["Book beach stays early for long weekends.", "North Goa works better for nightlife, South Goa for quieter resorts.", "Scooter rentals are still the most efficient local transport."],
    estimatedCostFromIndia: { budget: 25000, comfort: 50000, premium: 110000 },
  },
  {
    slug: "kerala",
    name: "Kerala",
    country: "India",
    category: "domestic",
    overview: "Kerala is best positioned as a scenic domestic circuit combining Kochi, Munnar, Alleppey, and Thekkady with strong family and honeymoon demand.",
    bestTime: "October to March",
    visaSummary: "No visa required for domestic Indian travelers.",
    idealDurations: [5, 7, 10],
    themes: seoThemes,
    attractions: ["Alleppey Backwaters", "Munnar Tea Gardens", "Fort Kochi", "Periyar National Park", "Athirappilly Falls"],
    hotelSuggestions: ["Kumarakom lake resorts", "Fort Kochi boutique hotels", "Munnar mountain stays"],
    travelTips: ["Backwater houseboats are best reserved 4 to 6 weeks ahead in peak season.", "Split the trip into at least two bases to avoid long same-day transfers.", "Monsoon months are better for Ayurveda trips than sightseeing-heavy plans."],
    estimatedCostFromIndia: { budget: 35000, comfort: 70000, premium: 150000 },
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    country: "India",
    category: "domestic",
    overview: "Jaipur remains one of the strongest domestic city-break destinations thanks to forts, palaces, shopping, and wedding-season demand.",
    bestTime: "October to March",
    visaSummary: "No visa required for domestic Indian travelers.",
    idealDurations: [3, 5],
    themes: seoThemes,
    attractions: ["Amber Fort", "City Palace", "Hawa Mahal", "Nahargarh Fort", "Johari Bazaar"],
    hotelSuggestions: ["MI Road business hotels", "Old City heritage havelis", "Amer Road palace stays"],
    travelTips: ["Reserve premium heritage hotels early during wedding season.", "Plan fort visits in the morning to avoid heat.", "Old City shopping works best with half-day buffers."],
    estimatedCostFromIndia: { budget: 22000, comfort: 45000, premium: 100000 },
  },
  {
    slug: "ladakh",
    name: "Ladakh",
    country: "India",
    category: "domestic",
    overview: "Ladakh is a weather-sensitive domestic adventure product where route sequencing, acclimatization, and road-window timing matter more than raw itinerary density.",
    bestTime: "June to September",
    visaSummary: "No visa required for domestic Indian travelers, but inner-line permits may apply for specific regions.",
    idealDurations: [5, 7, 10],
    themes: ["family", "budget", "adventure", "luxury"],
    attractions: ["Pangong Lake", "Nubra Valley", "Leh Palace", "Khardung La", "Diskit Monastery"],
    hotelSuggestions: ["Leh town hotels", "Nubra camp stays", "Pangong lakeside camps"],
    travelTips: ["Keep day one light for acclimatization.", "Road conditions change weekly, so keep one flexible buffer day.", "Private SUVs outperform self-drive for reliability on remote sections."],
    estimatedCostFromIndia: { budget: 40000, comfort: 80000, premium: 165000 },
  },
  {
    slug: "thailand",
    name: "Thailand",
    country: "Thailand",
    category: "international",
    overview: "Thailand remains one of the highest-converting outbound destinations from India because it balances affordability, short-haul flight access, strong food demand, and mixed beach-city itineraries.",
    bestTime: "November to February",
    visaSummary: "Visa-free for Indian passport holders for short leisure trips at the time of writing.",
    idealDurations: [5, 7, 10],
    themes: seoThemes,
    attractions: ["Grand Palace", "Phi Phi Islands", "Wat Pho", "Chiang Mai Night Bazaar", "Railay Beach"],
    hotelSuggestions: ["Sukhumvit hotels", "Phuket beach resorts", "Chiang Mai old city stays"],
    travelTips: ["Bangkok plus one beach base works better than cramming three islands into a week.", "Phuket fares spike around New Year and long weekends.", "Street-food-heavy itineraries need neighborhood-level planning, not just city-level planning."],
    estimatedCostFromIndia: { budget: 55000, comfort: 95000, premium: 180000 },
  },
  {
    slug: "dubai",
    name: "Dubai",
    country: "United Arab Emirates",
    category: "international",
    overview: "Dubai is a high-intent outbound destination from India with strong short-haul demand, premium hotel monetization, and year-round search volume across shopping, family, and luxury travel intents.",
    bestTime: "November to March",
    visaSummary: "Indian passport holders typically need a UAE tourist visa or an eligible visa-on-arrival pathway depending on their residence status.",
    idealDurations: [3, 5, 7],
    themes: seoThemes,
    attractions: ["Burj Khalifa", "Dubai Mall", "Desert Safari", "Palm Jumeirah", "Dubai Marina"],
    hotelSuggestions: ["Downtown Dubai hotels", "Dubai Marina stays", "Palm Jumeirah resorts"],
    travelTips: ["Winter stays book out quickly around December peak weeks.", "Downtown is better for first-time visitors, Marina for longer leisure stays.", "Budget travelers should compare Deira and Al Barsha rather than beach areas."],
    estimatedCostFromIndia: { budget: 85000, comfort: 140000, premium: 260000 },
  },
  {
    slug: "japan",
    name: "Japan",
    country: "Japan",
    category: "international",
    overview: "Japan is a premium multi-city product where route logic, rail passes, and city sequencing materially affect both cost efficiency and traveler experience.",
    bestTime: "March to May and September to November",
    visaSummary: "Indian passport holders generally need a Japan tourist visa before departure.",
    idealDurations: [7, 10, 14],
    themes: seoThemes,
    attractions: ["Shibuya Crossing", "Fushimi Inari Taisha", "Arashiyama Bamboo Grove", "Osaka Castle", "teamLab Borderless"],
    hotelSuggestions: ["Shinjuku hotels", "Kyoto station stays", "Namba hotels"],
    travelTips: ["Tokyo-Kyoto-Osaka is still the strongest first-trip sequence.", "JR pass economics depend on actual intercity routing, not destination count alone.", "Cherry blossom and autumn foliage windows push both airfares and hotels significantly higher."],
    estimatedCostFromIndia: { budget: 150000, comfort: 240000, premium: 420000 },
  },
  {
    slug: "singapore",
    name: "Singapore",
    country: "Singapore",
    category: "international",
    overview: "Singapore is a short-haul, high-conversion city destination with strong family, food, and stopover traffic from India.",
    bestTime: "Year-round",
    visaSummary: "Indian passport holders generally need a Singapore tourist visa through an authorized channel.",
    idealDurations: [3, 5, 7],
    themes: seoThemes,
    attractions: ["Gardens by the Bay", "Marina Bay Sands", "Sentosa", "Singapore Zoo", "Chinatown"],
    hotelSuggestions: ["Marina Bay hotels", "Bugis business hotels", "Sentosa resorts"],
    travelTips: ["Three nights is enough for a first trip, but family travelers often benefit from five.", "Sentosa works best when paired with a city stay rather than used as the only base.", "Hotel ADR is high, so Booking.com conversion value per click is strong here."],
    estimatedCostFromIndia: { budget: 90000, comfort: 145000, premium: 260000 },
  },
  {
    slug: "vietnam",
    name: "Vietnam",
    country: "Vietnam",
    category: "international",
    overview: "Vietnam has strong cost-focused demand from India, especially across Hanoi, Da Nang, Hoi An, and Ho Chi Minh City multi-stop itineraries.",
    bestTime: "February to April and August to October",
    visaSummary: "Indian passport holders usually need an e-visa before travel.",
    idealDurations: [5, 7, 10],
    themes: seoThemes,
    attractions: ["Ha Long Bay", "Hoi An Ancient Town", "Golden Bridge", "Ho Chi Minh City", "Ninh Binh"],
    hotelSuggestions: ["Old Quarter Hanoi hotels", "Hoi An riverside stays", "Da Nang beach hotels"],
    travelTips: ["North-central-south combinations need at least seven days to feel balanced.", "Da Nang plus Hoi An is often a better short-trip pair than trying to include both Hanoi and Ho Chi Minh City.", "E-visa processing times should be built into trip start date suggestions."],
    estimatedCostFromIndia: { budget: 50000, comfort: 90000, premium: 170000 },
  },
  {
    slug: "bali",
    name: "Bali",
    country: "Indonesia",
    category: "international",
    overview: "Bali performs across honeymoon, luxury, family, and digital-nomad search intent, but trip quality depends heavily on picking the right stay clusters.",
    bestTime: "April to October",
    visaSummary: "Visa on arrival is typically available for Indian passport holders.",
    idealDurations: [5, 7, 10],
    themes: seoThemes,
    attractions: ["Uluwatu Temple", "Tegallalang Rice Terraces", "Seminyak", "Nusa Penida", "Ubud Monkey Forest"],
    hotelSuggestions: ["Ubud wellness stays", "Seminyak villas", "Nusa Dua resorts"],
    travelTips: ["Split-stay planning between Ubud and the coast works better than single-base trips.", "South Bali traffic can consume sightseeing time, so cluster day plans carefully.", "Villa demand spikes fast around honeymoon seasons and holiday peaks."],
    estimatedCostFromIndia: { budget: 70000, comfort: 120000, premium: 240000 },
  },
  {
    slug: "maldives",
    name: "Maldives",
    country: "Maldives",
    category: "international",
    overview: "Maldives is a high-value honeymoon and luxury product where resort transfers and meal plans are the main margin and conversion drivers.",
    bestTime: "November to April",
    visaSummary: "Indian passport holders usually receive visa on arrival for leisure travel.",
    idealDurations: [3, 5, 7],
    themes: ["honeymoon", "luxury", "family", "budget"],
    attractions: ["Overwater villas", "Snorkeling reefs", "Sunset cruises", "Sandbank excursions", "Private island dining"],
    hotelSuggestions: ["Maafushi guesthouses", "North Male Atoll resorts", "All-inclusive overwater villas"],
    travelTips: ["Transfer timing changes actual usable stay length, especially on short trips.", "Budget guesthouse islands and premium resort islands serve different traveler intents and should not be mixed in the same funnel copy.", "Meal-plan upsells matter more here than city activity add-ons."],
    estimatedCostFromIndia: { budget: 110000, comfort: 190000, premium: 450000 },
  },
  {
    slug: "switzerland",
    name: "Switzerland",
    country: "Switzerland",
    category: "international",
    overview: "Switzerland is a premium rail-first itinerary product where scenic routing and hotel base decisions directly influence user-perceived value.",
    bestTime: "June to September and December to February",
    visaSummary: "Indian passport holders usually need a Schengen visa before travel.",
    idealDurations: [7, 10, 14],
    themes: seoThemes,
    attractions: ["Jungfraujoch", "Lucerne Lake", "Zermatt", "Interlaken", "Glacier Express"],
    hotelSuggestions: ["Interlaken stays", "Lucerne lakeside hotels", "Zurich city hotels"],
    travelTips: ["Rail passes should be evaluated against actual day trip usage, not bought automatically.", "Interlaken works better as a mountain base than Zurich for scenic-heavy itineraries.", "Winter pages need separate positioning from summer scenic itineraries."],
    estimatedCostFromIndia: { budget: 180000, comfort: 280000, premium: 500000 },
  },
  {
    slug: "italy",
    name: "Italy",
    country: "Italy",
    category: "international",
    overview: "Italy is a classic multi-city Europe itinerary product with strong history, food, and honeymoon demand from India.",
    bestTime: "April to June and September to October",
    visaSummary: "Indian passport holders usually need a Schengen visa before travel.",
    idealDurations: [7, 10, 14],
    themes: seoThemes,
    attractions: ["Colosseum", "Venice canals", "Florence Duomo", "Amalfi Coast", "Vatican Museums"],
    hotelSuggestions: ["Rome historic center hotels", "Florence old town stays", "Venice canal-side hotels"],
    travelTips: ["Rome-Florence-Venice still converts best for first-time Italy itineraries.", "High-speed train routing is usually better than internal flights.", "Amalfi Coast only fits well in 10-day-plus itineraries."],
    estimatedCostFromIndia: { budget: 150000, comfort: 240000, premium: 420000 },
  },
  {
    slug: "paris",
    name: "Paris",
    country: "France",
    category: "international",
    overview: "Paris is an evergreen SEO destination because it supports itinerary, visa, trip-cost, honeymoon, and family content under a single high-intent market.",
    bestTime: "April to June and September to October",
    visaSummary: "Indian passport holders usually need a Schengen visa before travel.",
    idealDurations: [3, 5, 7],
    themes: seoThemes,
    attractions: ["Eiffel Tower", "Louvre Museum", "Montmartre", "Seine River Cruise", "Versailles"],
    hotelSuggestions: ["Opera district hotels", "Le Marais boutique stays", "Saint-Germain hotels"],
    travelTips: ["A 3-day Paris itinerary works only if Versailles is excluded or handled as optional.", "Central arrondissements support better walkability than peripheral budget stays for short trips.", "Museum scheduling needs timed-entry logic in production itineraries."],
    estimatedCostFromIndia: { budget: 140000, comfort: 220000, premium: 400000 },
  },
  {
    slug: "london",
    name: "London",
    country: "United Kingdom",
    category: "international",
    overview: "London supports strong city-break, family, luxury, and first-Europe-trip search demand while also working as a stopover anchor for the UK.",
    bestTime: "May to September",
    visaSummary: "Indian passport holders usually need a UK Standard Visitor visa before travel.",
    idealDurations: [3, 5, 7],
    themes: seoThemes,
    attractions: ["Tower of London", "Buckingham Palace", "British Museum", "West End", "Camden Market"],
    hotelSuggestions: ["South Bank hotels", "Paddington stays", "Covent Garden boutique hotels"],
    travelTips: ["Tube-connected central stays save time more reliably than outer-zone budget hotels on short trips.", "West End and museum demand lifts family itinerary value.", "UK visa lead time should be surfaced earlier in the planner than price optimization."],
    estimatedCostFromIndia: { budget: 150000, comfort: 240000, premium: 430000 },
  },
  {
    slug: "turkey",
    name: "Turkey",
    country: "Turkey",
    category: "international",
    overview: "Turkey combines city, culture, and landscape experiences in a way that performs well for value-conscious Indian outbound travelers.",
    bestTime: "April to June and September to November",
    visaSummary: "Indian passport holders usually need an e-visa or embassy-processed visa depending on eligibility.",
    idealDurations: [5, 7, 10],
    themes: seoThemes,
    attractions: ["Hagia Sophia", "Blue Mosque", "Cappadocia balloons", "Grand Bazaar", "Pamukkale"],
    hotelSuggestions: ["Sultanahmet hotels", "Cappadocia cave stays", "Bosphorus luxury hotels"],
    travelTips: ["Istanbul plus Cappadocia is the strongest first-trip funnel.", "Balloon availability makes Cappadocia itineraries sensitive to buffer days.", "The destination performs especially well on culture and food search themes."],
    estimatedCostFromIndia: { budget: 90000, comfort: 145000, premium: 260000 },
  },
  {
    slug: "morocco",
    name: "Morocco",
    country: "Morocco",
    category: "international",
    overview: "Morocco is a distinctive long-haul value destination with strong visual SEO appeal across desert, medina, and riad-focused content.",
    bestTime: "March to May and September to November",
    visaSummary: "Visa requirements vary; Indian passport holders typically need to confirm the latest pre-travel visa process.",
    idealDurations: [7, 10],
    themes: seoThemes,
    attractions: ["Marrakech medina", "Sahara Desert camps", "Chefchaouen", "Fez old city", "Atlas Mountains"],
    hotelSuggestions: ["Marrakech riads", "Chefchaouen boutique stays", "Sahara luxury camps"],
    travelTips: ["The destination works best as a circuit, not a single-city stay.", "Desert legs add transfer complexity and should be clearly surfaced in itinerary pages.", "Riad-style inventory converts better than generic hotel language for Morocco content."],
    estimatedCostFromIndia: { budget: 100000, comfort: 160000, premium: 290000 },
  },
  {
    slug: "europe",
    name: "Europe",
    country: "Multi-country Europe",
    category: "region",
    overview: "Europe functions as a high-volume region query where users often need help narrowing to the right countries, durations, and budget-fit routes from India.",
    bestTime: "April to June and September to October",
    visaSummary: "A Schengen visa is usually required for most Europe itineraries from India, with the UK handled separately.",
    idealDurations: [7, 10, 14],
    themes: seoThemes,
    attractions: ["Paris", "Amsterdam", "Rome", "Swiss Alps", "Prague"],
    hotelSuggestions: ["Paris city hotels", "Amsterdam canal-side stays", "Swiss scenic resorts"],
    travelTips: ["Region queries need country selection before day-by-day planning becomes useful.", "Train-first routing works best inside dense Western Europe itineraries.", "Visa, rail, and city-order logic should all be visible in funnel copy for Europe pages."],
    estimatedCostFromIndia: { budget: 160000, comfort: 260000, premium: 480000 },
  },
  {
    slug: "south-korea",
    name: "South Korea",
    country: "South Korea",
    category: "international",
    overview: "South Korea continues to grow in search demand from India across K-culture, city, shopping, and spring/autumn seasonal travel intent.",
    bestTime: "March to May and September to November",
    visaSummary: "Indian passport holders usually need pre-travel entry authorization or a visa depending on the latest rules.",
    idealDurations: [5, 7, 10],
    themes: seoThemes,
    attractions: ["Gyeongbokgung Palace", "Myeongdong", "Busan coast", "Bukchon Hanok Village", "N Seoul Tower"],
    hotelSuggestions: ["Myeongdong hotels", "Hongdae stays", "Busan beach hotels"],
    travelTips: ["Seoul plus Busan performs better than overloading short trips with too many internal moves.", "Seasonal pages around cherry blossoms and autumn foliage are especially strong SEO candidates.", "Shopping and food themes convert well for this market."],
    estimatedCostFromIndia: { budget: 110000, comfort: 175000, premium: 310000 },
  },
  {
    slug: "indonesia",
    name: "Indonesia",
    country: "Indonesia",
    category: "international",
    overview: "Indonesia is broader than Bali alone and supports SEO clusters around islands, temples, surf, and budget-friendly leisure travel from India.",
    bestTime: "April to October",
    visaSummary: "Visa rules vary by island routing, but Bali-focused leisure travel often uses visa-on-arrival workflows for Indian travelers.",
    idealDurations: [5, 7, 10],
    themes: seoThemes,
    attractions: ["Bali", "Ubud", "Nusa Penida", "Borobudur", "Komodo islands"],
    hotelSuggestions: ["Seminyak villas", "Ubud nature stays", "Jakarta transit hotels"],
    travelTips: ["If the user really means Bali, route content should say Bali instead of Indonesia to avoid intent mismatch.", "Island-hopping requires buffer time and realistic transfer planning.", "Search demand splits strongly between honeymoon and budget segments."],
    estimatedCostFromIndia: { budget: 70000, comfort: 120000, premium: 230000 },
  },
];
