import React from "react";
import { FileText } from "lucide-react";

export const metadata = {
  title: "Terms of Service — Safar AI",
  description: "Terms of service for Safar AI travel planning platform.",
};

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12">
      <div className="card p-8">
        <div className="flex items-center gap-3 mb-6">
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary-50">
            <FileText size={20} className="text-primary-600" />
          </div>
          <div>
            <h1 className="font-display text-2xl font-bold text-text-primary">Terms of Service</h1>
            <p className="text-xs text-text-muted">Last updated: March 2026</p>
          </div>
        </div>

        <div className="prose prose-sm max-w-none text-text-secondary space-y-4">
          <h2 className="text-sm font-semibold text-text-primary">1. Acceptance of Terms</h2>
          <p className="text-sm leading-relaxed">
            By using Safar AI, you agree to these Terms of Service. If you do not agree, please do not use our platform. Safar AI is a travel planning tool that helps you research and compare travel options.
          </p>

          <h2 className="text-sm font-semibold text-text-primary">2. Service Description</h2>
          <p className="text-sm leading-relaxed">
            Safar AI is an AI-powered travel planning platform that generates itineraries, compares flights and hotels from partner platforms, and provides travel recommendations. We are a planning and comparison tool — we do not process bookings directly. All bookings are completed on partner platforms (MakeMyTrip, Booking.com, Skyscanner, etc.).
          </p>

          <h2 className="text-sm font-semibold text-text-primary">3. Pricing & Affiliate Links</h2>
          <p className="text-sm leading-relaxed">
            Prices displayed on Safar AI are estimates sourced from partner platforms and may change. Final pricing is determined by the booking partner at the time of purchase. Safar AI may earn affiliate commissions from partner bookings at no extra cost to you. We are transparent about our affiliate relationships.
          </p>

          <h2 className="text-sm font-semibold text-text-primary">4. AI-Generated Content</h2>
          <p className="text-sm leading-relaxed">
            Trip itineraries, travel tips, and recommendations are generated by AI and should be used as guidance. While we strive for accuracy, AI-generated information may occasionally contain errors. Always verify important details (visa requirements, opening hours, safety advisories) with official sources before traveling.
          </p>

          <h2 className="text-sm font-semibold text-text-primary">5. User Accounts</h2>
          <p className="text-sm leading-relaxed">
            Creating an account is optional for basic trip planning. Account features include saving trips and downloading PDF itineraries. You are responsible for maintaining the security of your account credentials. We reserve the right to suspend accounts that violate these terms.
          </p>

          <h2 className="text-sm font-semibold text-text-primary">6. Limitation of Liability</h2>
          <p className="text-sm leading-relaxed">
            Safar AI provides travel planning assistance and is not responsible for the accuracy of third-party pricing, availability, or services. We are not liable for any losses arising from travel decisions made based on our recommendations. Travel involves inherent risks — always purchase appropriate travel insurance.
          </p>

          <h2 className="text-sm font-semibold text-text-primary">7. Intellectual Property</h2>
          <p className="text-sm leading-relaxed">
            The Safar AI brand, logo, and platform design are our intellectual property. AI-generated itineraries created for you are yours to use, share, and print. You may not reproduce the platform itself or use automated tools to scrape our content.
          </p>

          <h2 className="text-sm font-semibold text-text-primary">8. Governing Law</h2>
          <p className="text-sm leading-relaxed">
            These terms are governed by the laws of India. Any disputes shall be resolved in the courts of India. By using Safar AI, you consent to this jurisdiction.
          </p>
        </div>
      </div>
    </div>
  );
}
